//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NRA_ABIS_Service_Test_Application.NRA_ABIS_Service {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="NRA_ABIS_Service.INRA_ABIS_Service")]
    public interface INRA_ABIS_Service {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:49950/Services/NRA_ABIS_Service.svc/Is_Service_Running_Request", ReplyAction="http://localhost:49950/Services/NRA_ABIS_Service.svc/Is_Service_Running_Response")]
        bool Is_Service_Running();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:49950/Services/NRA_ABIS_Service.svc/Is_Service_Running_Request", ReplyAction="http://localhost:49950/Services/NRA_ABIS_Service.svc/Is_Service_Running_Response")]
        System.Threading.Tasks.Task<bool> Is_Service_RunningAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:49950/Services/NRA_ABIS_Service.svc/Biometric_Identification_Req" +
            "uest", ReplyAction="http://localhost:49950/Services/NRA_ABIS_Service.svc/Biometric_Identification_Res" +
            "ponse")]
        NRA_ABIS_Envelope.Response Biometric_Identification(NRA_ABIS_Envelope.Request Request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:49950/Services/NRA_ABIS_Service.svc/Biometric_Identification_Req" +
            "uest", ReplyAction="http://localhost:49950/Services/NRA_ABIS_Service.svc/Biometric_Identification_Res" +
            "ponse")]
        System.Threading.Tasks.Task<NRA_ABIS_Envelope.Response> Biometric_IdentificationAsync(NRA_ABIS_Envelope.Request Request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:49950/Services/NRA_ABIS_Service.svc/Biometric_Identification_Res" +
            "ult_Request", ReplyAction="http://localhost:49950/Services/NRA_ABIS_Service.svc/Biometric_Identification_Res" +
            "ult_Response")]
        NRA_ABIS_Envelope.Response Biometric_Identification_Result(NRA_ABIS_Envelope.Request Request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:49950/Services/NRA_ABIS_Service.svc/Biometric_Identification_Res" +
            "ult_Request", ReplyAction="http://localhost:49950/Services/NRA_ABIS_Service.svc/Biometric_Identification_Res" +
            "ult_Response")]
        System.Threading.Tasks.Task<NRA_ABIS_Envelope.Response> Biometric_Identification_ResultAsync(NRA_ABIS_Envelope.Request Request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:49950/Services/NRA_ABIS_Service.svc/Biometric_Information_Reques" +
            "t", ReplyAction="http://localhost:49950/Services/NRA_ABIS_Service.svc/Biometric_Information_Respon" +
            "se")]
        NRA_ABIS_Envelope.Response Biometric_Information(NRA_ABIS_Envelope.Request Request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:49950/Services/NRA_ABIS_Service.svc/Biometric_Information_Reques" +
            "t", ReplyAction="http://localhost:49950/Services/NRA_ABIS_Service.svc/Biometric_Information_Respon" +
            "se")]
        System.Threading.Tasks.Task<NRA_ABIS_Envelope.Response> Biometric_InformationAsync(NRA_ABIS_Envelope.Request Request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:49950/Services/NRA_ABIS_Service.svc/Fingerprint_Identification_R" +
            "equest", ReplyAction="http://localhost:49950/Services/NRA_ABIS_Service.svc/Fingerprint_Identification_R" +
            "esponse")]
        NRA_ABIS_Envelope.Response Fingerprint_Identification(NRA_ABIS_Envelope.Request Request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:49950/Services/NRA_ABIS_Service.svc/Fingerprint_Identification_R" +
            "equest", ReplyAction="http://localhost:49950/Services/NRA_ABIS_Service.svc/Fingerprint_Identification_R" +
            "esponse")]
        System.Threading.Tasks.Task<NRA_ABIS_Envelope.Response> Fingerprint_IdentificationAsync(NRA_ABIS_Envelope.Request Request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:49950/Services/NRA_ABIS_Service.svc/Fingerprint_Identification_R" +
            "esult_Request", ReplyAction="http://localhost:49950/Services/NRA_ABIS_Service.svc/Fingerprint_Identification_R" +
            "esult_Response")]
        NRA_ABIS_Envelope.Response Fingerprint_Identification_Result(NRA_ABIS_Envelope.Request Request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:49950/Services/NRA_ABIS_Service.svc/Fingerprint_Identification_R" +
            "esult_Request", ReplyAction="http://localhost:49950/Services/NRA_ABIS_Service.svc/Fingerprint_Identification_R" +
            "esult_Response")]
        System.Threading.Tasks.Task<NRA_ABIS_Envelope.Response> Fingerprint_Identification_ResultAsync(NRA_ABIS_Envelope.Request Request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:49950/Services/NRA_ABIS_Service.svc/Fingerprint_Insert_Request", ReplyAction="http://localhost:49950/Services/NRA_ABIS_Service.svc/Fingerprint_Insert_Response")]
        NRA_ABIS_Envelope.Response Fingerprint_Insert(NRA_ABIS_Envelope.Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:49950/Services/NRA_ABIS_Service.svc/Fingerprint_Insert_Request", ReplyAction="http://localhost:49950/Services/NRA_ABIS_Service.svc/Fingerprint_Insert_Response")]
        System.Threading.Tasks.Task<NRA_ABIS_Envelope.Response> Fingerprint_InsertAsync(NRA_ABIS_Envelope.Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:49950/Services/NRA_ABIS_Service.svc/Fingerprint_Template_Request" +
            "", ReplyAction="http://localhost:49950/Services/NRA_ABIS_Service.svc/Fingerprint_Template_Respons" +
            "e")]
        NRA_ABIS_Envelope.Response Fingerprint_Template(NRA_ABIS_Envelope.Request Request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:49950/Services/NRA_ABIS_Service.svc/Fingerprint_Template_Request" +
            "", ReplyAction="http://localhost:49950/Services/NRA_ABIS_Service.svc/Fingerprint_Template_Respons" +
            "e")]
        System.Threading.Tasks.Task<NRA_ABIS_Envelope.Response> Fingerprint_TemplateAsync(NRA_ABIS_Envelope.Request Request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:49950/Services/NRA_ABIS_Service.svc/Fingerprint_Verification_Req" +
            "uest", ReplyAction="http://localhost:49950/Services/NRA_ABIS_Service.svc/Fingerprint_Verification_Res" +
            "ponse")]
        NRA_ABIS_Envelope.Response Fingerprint_Verification(NRA_ABIS_Envelope.Request Request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:49950/Services/NRA_ABIS_Service.svc/Fingerprint_Verification_Req" +
            "uest", ReplyAction="http://localhost:49950/Services/NRA_ABIS_Service.svc/Fingerprint_Verification_Res" +
            "ponse")]
        System.Threading.Tasks.Task<NRA_ABIS_Envelope.Response> Fingerprint_VerificationAsync(NRA_ABIS_Envelope.Request Request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:49950/Services/NRA_ABIS_Service.svc/Portrait_Identification_Requ" +
            "est", ReplyAction="http://localhost:49950/Services/NRA_ABIS_Service.svc/Portrait_Identification_Resp" +
            "onse")]
        NRA_ABIS_Envelope.Response Portrait_Identification(NRA_ABIS_Envelope.Request Request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:49950/Services/NRA_ABIS_Service.svc/Portrait_Identification_Requ" +
            "est", ReplyAction="http://localhost:49950/Services/NRA_ABIS_Service.svc/Portrait_Identification_Resp" +
            "onse")]
        System.Threading.Tasks.Task<NRA_ABIS_Envelope.Response> Portrait_IdentificationAsync(NRA_ABIS_Envelope.Request Request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:49950/Services/NRA_ABIS_Service.svc/Portrait_Identification_Resu" +
            "lt_Request", ReplyAction="http://localhost:49950/Services/NRA_ABIS_Service.svc/Portrait_Identification_Resu" +
            "lt_Response")]
        NRA_ABIS_Envelope.Response Portrait_Identification_Result(NRA_ABIS_Envelope.Request Request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:49950/Services/NRA_ABIS_Service.svc/Portrait_Identification_Resu" +
            "lt_Request", ReplyAction="http://localhost:49950/Services/NRA_ABIS_Service.svc/Portrait_Identification_Resu" +
            "lt_Response")]
        System.Threading.Tasks.Task<NRA_ABIS_Envelope.Response> Portrait_Identification_ResultAsync(NRA_ABIS_Envelope.Request Request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:49950/Services/NRA_ABIS_Service.svc/Portrait_Verification_Reques" +
            "t", ReplyAction="http://localhost:49950/Services/NRA_ABIS_Service.svc/Portrait_Verification_Respon" +
            "se")]
        NRA_ABIS_Envelope.Response Portrait_Verification(NRA_ABIS_Envelope.Request Request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:49950/Services/NRA_ABIS_Service.svc/Portrait_Verification_Reques" +
            "t", ReplyAction="http://localhost:49950/Services/NRA_ABIS_Service.svc/Portrait_Verification_Respon" +
            "se")]
        System.Threading.Tasks.Task<NRA_ABIS_Envelope.Response> Portrait_VerificationAsync(NRA_ABIS_Envelope.Request Request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:49950/Services/NRA_ABIS_Service.svc/Delete_Record_Request", ReplyAction="http://localhost:49950/Services/NRA_ABIS_Service.svc/Delete_Record_Response")]
        NRA_ABIS_Envelope.Response Delete_Record(NRA_ABIS_Envelope.Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:49950/Services/NRA_ABIS_Service.svc/Delete_Record_Request", ReplyAction="http://localhost:49950/Services/NRA_ABIS_Service.svc/Delete_Record_Response")]
        System.Threading.Tasks.Task<NRA_ABIS_Envelope.Response> Delete_RecordAsync(NRA_ABIS_Envelope.Request request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface INRA_ABIS_ServiceChannel : NRA_ABIS_Service_Test_Application.NRA_ABIS_Service.INRA_ABIS_Service, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NRA_ABIS_ServiceClient : System.ServiceModel.ClientBase<NRA_ABIS_Service_Test_Application.NRA_ABIS_Service.INRA_ABIS_Service>, NRA_ABIS_Service_Test_Application.NRA_ABIS_Service.INRA_ABIS_Service {
        
        public NRA_ABIS_ServiceClient() {
        }
        
        public NRA_ABIS_ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NRA_ABIS_ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NRA_ABIS_ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NRA_ABIS_ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool Is_Service_Running() {
            return base.Channel.Is_Service_Running();
        }
        
        public System.Threading.Tasks.Task<bool> Is_Service_RunningAsync() {
            return base.Channel.Is_Service_RunningAsync();
        }
        
        public NRA_ABIS_Envelope.Response Biometric_Identification(NRA_ABIS_Envelope.Request Request) {
            return base.Channel.Biometric_Identification(Request);
        }
        
        public System.Threading.Tasks.Task<NRA_ABIS_Envelope.Response> Biometric_IdentificationAsync(NRA_ABIS_Envelope.Request Request) {
            return base.Channel.Biometric_IdentificationAsync(Request);
        }
        
        public NRA_ABIS_Envelope.Response Biometric_Identification_Result(NRA_ABIS_Envelope.Request Request) {
            return base.Channel.Biometric_Identification_Result(Request);
        }
        
        public System.Threading.Tasks.Task<NRA_ABIS_Envelope.Response> Biometric_Identification_ResultAsync(NRA_ABIS_Envelope.Request Request) {
            return base.Channel.Biometric_Identification_ResultAsync(Request);
        }
        
        public NRA_ABIS_Envelope.Response Biometric_Information(NRA_ABIS_Envelope.Request Request) {
            return base.Channel.Biometric_Information(Request);
        }
        
        public System.Threading.Tasks.Task<NRA_ABIS_Envelope.Response> Biometric_InformationAsync(NRA_ABIS_Envelope.Request Request) {
            return base.Channel.Biometric_InformationAsync(Request);
        }
        
        public NRA_ABIS_Envelope.Response Fingerprint_Identification(NRA_ABIS_Envelope.Request Request) {
            return base.Channel.Fingerprint_Identification(Request);
        }
        
        public System.Threading.Tasks.Task<NRA_ABIS_Envelope.Response> Fingerprint_IdentificationAsync(NRA_ABIS_Envelope.Request Request) {
            return base.Channel.Fingerprint_IdentificationAsync(Request);
        }
        
        public NRA_ABIS_Envelope.Response Fingerprint_Identification_Result(NRA_ABIS_Envelope.Request Request) {
            return base.Channel.Fingerprint_Identification_Result(Request);
        }
        
        public System.Threading.Tasks.Task<NRA_ABIS_Envelope.Response> Fingerprint_Identification_ResultAsync(NRA_ABIS_Envelope.Request Request) {
            return base.Channel.Fingerprint_Identification_ResultAsync(Request);
        }
        
        public NRA_ABIS_Envelope.Response Fingerprint_Insert(NRA_ABIS_Envelope.Request request) {
            return base.Channel.Fingerprint_Insert(request);
        }
        
        public System.Threading.Tasks.Task<NRA_ABIS_Envelope.Response> Fingerprint_InsertAsync(NRA_ABIS_Envelope.Request request) {
            return base.Channel.Fingerprint_InsertAsync(request);
        }
        
        public NRA_ABIS_Envelope.Response Fingerprint_Template(NRA_ABIS_Envelope.Request Request) {
            return base.Channel.Fingerprint_Template(Request);
        }
        
        public System.Threading.Tasks.Task<NRA_ABIS_Envelope.Response> Fingerprint_TemplateAsync(NRA_ABIS_Envelope.Request Request) {
            return base.Channel.Fingerprint_TemplateAsync(Request);
        }
        
        public NRA_ABIS_Envelope.Response Fingerprint_Verification(NRA_ABIS_Envelope.Request Request) {
            return base.Channel.Fingerprint_Verification(Request);
        }
        
        public System.Threading.Tasks.Task<NRA_ABIS_Envelope.Response> Fingerprint_VerificationAsync(NRA_ABIS_Envelope.Request Request) {
            return base.Channel.Fingerprint_VerificationAsync(Request);
        }
        
        public NRA_ABIS_Envelope.Response Portrait_Identification(NRA_ABIS_Envelope.Request Request) {
            return base.Channel.Portrait_Identification(Request);
        }
        
        public System.Threading.Tasks.Task<NRA_ABIS_Envelope.Response> Portrait_IdentificationAsync(NRA_ABIS_Envelope.Request Request) {
            return base.Channel.Portrait_IdentificationAsync(Request);
        }
        
        public NRA_ABIS_Envelope.Response Portrait_Identification_Result(NRA_ABIS_Envelope.Request Request) {
            return base.Channel.Portrait_Identification_Result(Request);
        }
        
        public System.Threading.Tasks.Task<NRA_ABIS_Envelope.Response> Portrait_Identification_ResultAsync(NRA_ABIS_Envelope.Request Request) {
            return base.Channel.Portrait_Identification_ResultAsync(Request);
        }
        
        public NRA_ABIS_Envelope.Response Portrait_Verification(NRA_ABIS_Envelope.Request Request) {
            return base.Channel.Portrait_Verification(Request);
        }
        
        public System.Threading.Tasks.Task<NRA_ABIS_Envelope.Response> Portrait_VerificationAsync(NRA_ABIS_Envelope.Request Request) {
            return base.Channel.Portrait_VerificationAsync(Request);
        }
        
        public NRA_ABIS_Envelope.Response Delete_Record(NRA_ABIS_Envelope.Request request) {
            return base.Channel.Delete_Record(request);
        }
        
        public System.Threading.Tasks.Task<NRA_ABIS_Envelope.Response> Delete_RecordAsync(NRA_ABIS_Envelope.Request request) {
            return base.Channel.Delete_RecordAsync(request);
        }
    }
}
